# Generated by Django 3.1.7 on 2021-05-12 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210511_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.reportlisting'),
        ),
    ]
