# Generated by Django 3.1.7 on 2021-05-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_listing_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo',
        ),
    ]
