# Generated by Django 3.1.7 on 2021-05-12 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_conversation_report'),
        ('pages', '0008_remove_listing_photo'),
    ]

    operations = [
    ]
