# Generated by Django 3.1.7 on 2021-03-29 14:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, unique=True, verbose_name='ISBN')),
                ('edition', models.CharField(max_length=5)),
                ('pub_year', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='date_added',
            field=models.DateField(auto_now_add=True, help_text='date added'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='unique id for this listing', primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('condition', models.CharField(blank=True, choices=[(1, 'New'), (2, 'Like New'), (3, 'Lightly Used'), (4, 'Moderately Used'), (5, 'Heavily Used')], default=1, help_text='Book condition', max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pages.book')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.user')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
