# Generated by Django 3.1.7 on 2021-04-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='state',
            field=models.CharField(blank=True, choices=[('0', 'In Progress'), ('1', 'Completed (Pending)'), ('2', 'Completed')], default=0, help_text='Conversation status', max_length=1),
        ),
    ]
