# Generated by Django 3.1.7 on 2021-04-11 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0002_auto_20210329_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='posted_by',
        ),
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(blank=True, choices=[('1', 'New'), ('2', 'Like New'), ('3', 'Lightly Used'), ('4', 'Moderately Used'), ('5', 'Heavily Used')], default=1, help_text='Book condition', max_length=1),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
