# Generated by Django 3.1.7 on 2021-05-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_conversation_state'),
        ('pages', '0003_profile'),
    ]

    operations = [
    ]
