# Generated by Django 3.1.7 on 2021-04-22 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_listing_price'),
        ('pages', '0007_auto_20210420_1618'),
    ]

    operations = [
    ]
