# Generated by Django 3.1.7 on 2021-04-26 20:39

from django.db import migrations
import shortuuidfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_merge_20210421_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='unique id for this listing', max_length=22, primary_key=True, serialize=False),
        ),
    ]
