# Generated by Django 3.1.7 on 2021-04-26 21:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210426_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='unique id for this listing', primary_key=True, serialize=False),
        ),
    ]
