# Generated by Django 3.1.7 on 2021-04-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
        migrations.AddField(
            model_name='listing',
            name='hide_listing',
            field=models.BooleanField(default=False),
        ),
    ]
