# Generated by Django 3.1.7 on 2021-04-27 17:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0014_auto_20210427_1314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='ReportListing',
        ),
    ]
