# Generated by Django 3.1.7 on 2021-04-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20210427_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='times_reported',
            field=models.SmallIntegerField(default=0),
        ),
    ]
