# Generated by Django 3.1.7 on 2021-04-27 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_listing_times_reported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportlisting',
            name='reported_listing',
        ),
        migrations.AddField(
            model_name='listing',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.reportlisting'),
        ),
    ]
